package uom.ict.mdp;

import android.app.Activity;
import android.content.Intent;
import android.os.Bundle;
import android.view.Menu;
import android.view.MenuItem;
import android.view.View;
import android.widget.AdapterView;
import android.widget.ArrayAdapter;
import android.widget.ImageButton;
import android.widget.ImageView;
import android.widget.Spinner;
import android.widget.Toast;


public class Intro extends Activity {

    public final static String EVENT_TITLE = "event";

    private Spinner spinner;
    private ImageView eventImage;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_intro);
        spinner = (Spinner) findViewById(R.id.spinner);
        ArrayAdapter adapter = ArrayAdapter.createFromResource(this, R.array.intents, android.R.layout.simple_spinner_item);
        adapter.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);
        spinner.setAdapter(adapter);
        eventImage = (ImageView) findViewById(R.id.intro_image);

        spinner.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener()
        {

            @Override
            public void onItemSelected(AdapterView<?> parent, View view, int position, long id)
            {
                int eventCase = spinner.getSelectedItemPosition()+1;


                switch (eventCase)
                {
                    case 1:
                        eventImage.setImageDrawable(getResources().getDrawable(R.drawable.nottebianca));
                        break;
                    case 2:
                        eventImage.setImageDrawable(getResources().getDrawable(R.drawable.birgu));
                        break;
                    case 3:
                        eventImage.setImageDrawable(getResources().getDrawable(R.drawable.birgu));
                        break;
            }
        }

            @Override
            public void onNothingSelected(AdapterView<?> parent)
            {
                // AUTOGENERATED STUB
            }

        });

        //Intent on The images




    }



    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        // Inflate the menu; this adds items to the action bar if it is present.
        getMenuInflater().inflate(R.menu.menu_intro, menu);

        return true;
    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        // Handle action bar item clicks here. The action bar will
        // automatically handle clicks on the Home/Up button, so long
        // as you specify a parent activity in AndroidManifest.xml.
        int id = item.getItemId();

        //noinspection SimplifiableIfStatement
        if (id == R.id.action_settings) {
            return true;
        }

        return super.onOptionsItemSelected(item);
    }


    public void imageClick(View v) {
        int pos = spinner.getSelectedItemPosition() + 1;
        Intent i = new Intent(this,MainActivity.class);

        switch (pos) {
            case 1:
                Toast.makeText(getBaseContext(),""+spinner.getSelectedItemId(),Toast.LENGTH_SHORT).show();
                i.putExtra(EVENT_TITLE, spinner.getSelectedItemPosition());
                startActivity(i);
                break;
            case 2:
                Toast.makeText(getBaseContext(),""+spinner.getSelectedItemId(),Toast.LENGTH_SHORT).show();
                i.putExtra(EVENT_TITLE, spinner.getSelectedItemPosition());
                startActivity(i);
                break;
        }

    }
}
